version: '3.8'
services:
    db:
        container_name: mysql
        platform: linux/x86_64
        image: mysql:8.0
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - "TZ=Asia/Tokyo"
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - mysql_data:/var/lib/mysql
            - ./db/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
        ports:
            - ${MYSQL_PORT}:3306

    app:
        container_name: todo
        build: .
        tty: true
        ports:
            - "9000:9000"
        volumes:
            - .:/work
        depends_on:
            - db
volumes:
    mysql_data: